/**
 * Drip campaign sequence configuration.
 * Maps (list, day) → Listmonk transactional template ID.
 *
 * Template IDs are generated by setup_listmonk.ts and stored in environment variables.
 * Content edits: Listmonk UI → Campaigns → Templates. No code changes needed.
 */

import { listmonkConfig } from '../lib/config.js';

export interface DripStep {
  day: number;
  templateId: number;
  fromEmail?: string;
  /** If set, the step is only sent when this subscriber attribute is present (truthy). */
  requiredAttrib?: string;
}

export interface DripSequence {
  name: string;
  listId: number;
  dateAttrib?: string;
  steps: DripStep[];
}

const lists = listmonkConfig.lists;
const templates = listmonkConfig.templates;

export const SEQUENCES: DripSequence[] = [
  {
    name: 'free-new',
    listId: lists.freeNew,
    dateAttrib: 'signup_at',
    steps: [
      { day: 0, templateId: templates.freeNewDay0Welcome },
      { day: 2, templateId: templates.freeNewDay2Security },
      { day: 5, templateId: templates.freeNewDay5Value },
    ],
  },
  {
    name: 'free-scanned',
    listId: lists.freeScanned,
    dateAttrib: 'scan_completed_at',
    steps: [
      { day: 0, templateId: templates.freeScannedDay0Results },
      { day: 2, templateId: templates.freeScannedDay2Critical },
      { day: 5, templateId: templates.freeScannedDay5Cost },
      { day: 10, templateId: templates.freeScannedDay10Breakup, fromEmail: 'Maksim <maksim@scanorbit.cloud>' },
    ],
  },
  {
    name: 'trial-new',
    listId: lists.trialNew,
    dateAttrib: 'trial_started_at',
    steps: [
      { day: 0, templateId: templates.trialNewDay0Welcome },
      { day: 3, templateId: templates.trialNewDay3Stuck },
    ],
  },
  {
    name: 'trial-active',
    listId: lists.trialActive,
    dateAttrib: 'trial_started_at',
    steps: [
      { day: 3, templateId: templates.trialActiveDay3Deepen },
      { day: 5, templateId: templates.trialActiveDay5Warning },
      { day: 6, templateId: templates.trialActiveDay6Lastday },
      { day: 9, templateId: templates.trialActiveDay9Winback, fromEmail: 'Maksim <maksim@scanorbit.cloud>', requiredAttrib: 'trial_cancelled_at' },
    ],
  },
  {
    name: 'subscribers',
    listId: lists.subscribers,
    dateAttrib: 'subscribed_at',
    steps: [
      { day: 0, templateId: templates.subsDay0Welcome, fromEmail: 'Maksim <maksim@scanorbit.cloud>' },
      { day: 3, templateId: templates.subsDay3Security, fromEmail: 'Maksim <maksim@scanorbit.cloud>' },
      { day: 7, templateId: templates.subsDay7Cost, fromEmail: 'Maksim <maksim@scanorbit.cloud>' },
      { day: 11, templateId: templates.subsDay11Gdpr, fromEmail: 'Maksim <maksim@scanorbit.cloud>' },
      { day: 16, templateId: templates.subsDay16SocialProof, fromEmail: 'Maksim <maksim@scanorbit.cloud>' },
      { day: 21, templateId: templates.subsDay21FinalCta, fromEmail: 'Maksim <maksim@scanorbit.cloud>' },
    ],
  },
  {
    name: 'cold-leads',
    listId: lists.coldLeads,
    dateAttrib: 'imported_at',
    steps: [
      { day: 0, templateId: templates.coldDay0Pain, fromEmail: 'Maksim <maksim@scanorbit.cloud>' },
      { day: 4, templateId: templates.coldDay4Gdpr, fromEmail: 'Maksim <maksim@scanorbit.cloud>' },
      { day: 10, templateId: templates.coldDay10Breakup, fromEmail: 'Maksim <maksim@scanorbit.cloud>' },
    ],
  },
  {
    name: 'paid-pro',
    listId: lists.paidPro,
    dateAttrib: 'paid_at',
    steps: [
      { day: 0, templateId: templates.paidProDay0Welcome },
    ],
  },
  {
    name: 'paid-team',
    listId: lists.paidTeam,
    dateAttrib: 'paid_at',
    steps: [
      { day: 0, templateId: templates.paidTeamDay0Welcome },
    ],
  },
];
