/**
 * Drip campaign sequence configuration.
 * Maps (list, day) → Listmonk transactional template ID.
 *
 * Template IDs were generated by setup_listmonk.ts.
 * Content edits: Listmonk UI → Campaigns → Templates. No code changes needed.
 */

import { listmonkConfig } from '../lib/config.js';

export interface DripStep {
  day: number;
  templateId: number;
  fromEmail?: string;
}

export interface DripSequence {
  name: string;
  listId: number;
  dateAttrib?: string;
  steps: DripStep[];
}

const lists = listmonkConfig.lists;

export const SEQUENCES: DripSequence[] = [
  {
    name: 'free-new',
    listId: lists.freeNew,
    steps: [
      { day: 0, templateId: 41 },  // free-new-day0-welcome
      { day: 2, templateId: 42 },  // free-new-day2-security
      { day: 5, templateId: 43 },  // free-new-day5-value
    ],
  },
  {
    name: 'free-scanned',
    listId: lists.freeScanned,
    dateAttrib: 'scan_completed_at',
    steps: [
      { day: 0, templateId: 44 },  // free-scanned-day0-results
      { day: 2, templateId: 45 },  // free-scanned-day2-critical
      { day: 5, templateId: 46 },  // free-scanned-day5-cost
      { day: 10, templateId: 47, fromEmail: 'Maksim <maksim@scanorbit.cloud>' }, // free-scanned-day10-breakup
    ],
  },
  {
    name: 'trial-new',
    listId: lists.trialNew,
    steps: [
      { day: 0, templateId: 48 },  // trial-new-day0-welcome
      { day: 3, templateId: 49 },  // trial-new-day3-stuck
    ],
  },
  {
    name: 'trial-active',
    listId: lists.trialActive,
    dateAttrib: 'trial_started_at',
    steps: [
      { day: 3, templateId: 50 },  // trial-active-day3-deepen
      { day: 5, templateId: 51 },  // trial-active-day5-warning
      { day: 6, templateId: 52 },  // trial-active-day6-lastday
      { day: 9, templateId: 53, fromEmail: 'Maksim <maksim@scanorbit.cloud>' }, // trial-active-day9-winback
    ],
  },
  {
    name: 'subscribers',
    listId: lists.subscribers,
    steps: [
      { day: 0, templateId: 35 },  // subs-day0-welcome
      { day: 3, templateId: 36 },  // subs-day3-security
      { day: 7, templateId: 37 },  // subs-day7-cost
      { day: 11, templateId: 38 }, // subs-day11-gdpr
      { day: 16, templateId: 39 }, // subs-day16-social-proof
      { day: 21, templateId: 40 }, // subs-day21-final-cta
    ],
  },
  {
    name: 'cold-leads',
    listId: lists.coldLeads,
    steps: [
      { day: 0, templateId: 32, fromEmail: 'Maksim <maksim@scanorbit.cloud>' },  // cold-day0-pain
      { day: 4, templateId: 33, fromEmail: 'Maksim <maksim@scanorbit.cloud>' },  // cold-day4-gdpr
      { day: 10, templateId: 34, fromEmail: 'Maksim <maksim@scanorbit.cloud>' }, // cold-day10-breakup
    ],
  },
  {
    name: 'paid-pro',
    listId: lists.paidPro,
    steps: [
      { day: 0, templateId: 54 },  // paid-pro-day0-welcome
    ],
  },
  {
    name: 'paid-team',
    listId: lists.paidTeam,
    steps: [
      { day: 0, templateId: 55 },  // paid-team-day0-welcome
    ],
  },
];
