all:
  vars:
    ansible_user: deploy
    ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
    deploy_dir: /opt/scanorbit

  children:
    jump:
      hosts:
        ci:
          ansible_host: ci.scanorbit.cloud

    app:
      hosts:
        server:
          ansible_host: "{{ app_private_ip | default('10.10.0.3') }}"
          ansible_ssh_common_args: >-
            -o StrictHostKeyChecking=accept-new
            -o ProxyJump=deploy@ci.scanorbit.cloud
